Repository Thenlie/Streamability, pull requests merged in 2022-12, with the labels that each got.

#146 Update delete profile function to also delete user account
  src/supabase/profiles.ts
Labels: type: enhancement

#147 70 feat route protection
  .githooks/pre-commit
  src/AppWrapper.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/screens/DashboardScreen.tsx
Labels: type: feature

#151 Redirect user on auth changes. Clear data from local storage.
  src/AppWrapper.tsx
  src/components/Navigation.tsx
  src/hooks/context.ts
  src/screens/DashboardScreen.tsx
  src/supabase/profiles.ts
Labels: type: enhancement

#153 Update app color on theme change
  index.html
  src/index.css
  tailwind.config.cjs
Labels: type: design, type: enhancement

#157 149 Enhance Auth Forms
  .githooks/pre-commit
  src/App.css
  src/AppWrapper.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/index.css
  src/screens/AuthScreen.tsx
Labels: type: enhancement

#159 98 feat details page
  src/__tests__/routes.tsx
  src/components/ShowCard.tsx
  src/helpers/getMovieUtils.ts
  src/main.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb.ts
Labels: type: feature

#165 Update AppWrapper.tsx
  src/AppWrapper.tsx
Labels: type: bug

#167 Updated lint indent from tab to 4 space
  .eslintrc.json
  src/AppWrapper.tsx
  src/__tests__/components/assets/movieData.ts
  src/__tests__/components/component.test.tsx
  src/__tests__/routes.tsx
  src/__tests__/screens/screen.test.tsx
  src/__tests__/setup.ts
  src/components/ErrorMessage.tsx
  src/components/Navigation.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/SideNavigator.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/helpers/getMovieUtils.ts
  src/hooks/context.ts
  src/hooks/index.ts
  src/main.tsx
  src/screens/AuthScreen.tsx
  src/screens/DashboardScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/index.ts
  src/supabase/profiles.ts
  src/types/index.ts
  vite.config.ts
  vitest.config.ts
Labels: type: refactor

#168 1.3 Main merge
  .eslintrc.json
  .githooks/pre-commit
  .github/dependabot.yml
  docs/contribution-guidelines.md
  docs/project-board.md
  index.html
  src/App.css
  src/AppWrapper.tsx
  src/__tests__/components/assets/movieData.ts
  src/__tests__/components/component.test.tsx
  src/__tests__/routes.tsx
  src/__tests__/screens/screen.test.tsx
  src/__tests__/setup.ts
  src/components/ErrorMessage.tsx
  src/components/Navigation.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/SideNavigator.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/helpers/getMovieUtils.ts
  src/hooks/context.ts
  src/hooks/index.ts
  src/index.css
  src/main.tsx
  src/screens/AuthScreen.tsx
  src/screens/DashboardScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/index.ts
  src/supabase/profiles.ts
  src/types/index.ts
  src/types/tmdb.ts
  tailwind.config.cjs
  vite.config.ts
  vitest.config.ts
Labels: type: feature

#169 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/test-coverage.md
Labels: type: documentation

#186 Create date util unit tests
  src/__tests__/utilities/utilities.test.tsx
  src/helpers/dateFormatUtils.ts
Labels: type: testing

#188 175 bug queue
  src/components/ShowCard.tsx
Labels: type: bug

#190 177 bug US
  src/screens/ShowDetailsScreen.tsx
Labels: type: bug

#191 Fixed duplication bug
  .eslintrc.json
  src/__tests__/screens/assets/movieData.json
  src/__tests__/screens/assets/searchData.json
  src/__tests__/screens/screen.test.tsx
  src/components/ShowCard.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb.ts
Labels: type: bug

#192 Update markdown of issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/test-coverage.md
Labels: type: documentation, tag: help wanted

#200 116 screen testing
  src/__tests__/screens/assets/providerData.json
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/__tests__/screens/screen.test.tsx
  src/components/Navigation.tsx
  src/components/ShowCard.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: testing

#202 Resolve bug by querying new data if none exists
  src/screens/ShowDetailsScreen.tsx
Labels: type: bug

#206 161 feat logo
  src/__tests__/components/component.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/components/Providers.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: feature, type: enhancement

#207 Prettier setup
  .eslintrc.json
  .githooks/post-commit
  .githooks/pre-commit
  .prettierrc.json
  package-lock.json
  package.json
  src/AppWrapper.tsx
  src/__tests__/components/assets/movieData.ts
  src/__tests__/components/component.test.tsx
  src/__tests__/routes.tsx
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/__tests__/setup.ts
  src/__tests__/utilities/utilities.test.tsx
  src/components/ErrorMessage.tsx
  src/components/Navigation.tsx
  src/components/Providers.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/SideNavigator.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/helpers/dateFormatUtils.ts
  src/helpers/getMovieUtils.ts
  src/helpers/supabaseClient.ts
  src/hooks/context.ts
  src/hooks/index.ts
  src/main.tsx
  src/screens/AuthScreen.tsx
  src/screens/DashboardScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/supabase/profiles.ts
  src/types/index.ts
  src/types/supabase.ts
  src/types/tmdb.ts
  vite.config.ts
  vitest.config.ts
Labels: type: refactor

#208 154 Implement Top Navigation
  .eslintignore
  src/App.css
  src/AppWrapper.tsx
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/components/Navigation.tsx
  src/components/SearchInput.tsx
  src/index.css
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  tailwind.config.cjs
Labels: type: enhancement

#220 Dependabot update
  .github/dependabot.yml
Labels: dependencies

#218 203 bug empty search
  src/components/SearchInput.tsx
  src/screens/SearchResultsScreen.tsx
Labels: type: bug

#211 Fix bug where 'No providers' message flashes briefly on all screens
  src/components/Providers.tsx
  src/types/tmdb.ts
Labels: type: bug

#223 114 Feature update queue buttons
  src/__tests__/screens/movieScreen.test.tsx
  src/components/ShowCard.tsx
Labels: type: feature, type: enhancement

#225 99 feat gallery
  src/components/Navigation.tsx
  src/helpers/getMovieUtils.ts
  src/main.tsx
  src/screens/DiscoverScreen.tsx
  src/screens/index.ts
Labels: type: feature
