Repository Thenlie/Streamability, pull requests merged in 2022-11, with the labels that each got.

#45 Create basic client directory structure. Update README.md.
  README.md
  src/App.css
  src/App.tsx
  src/components/SearchInput.tsx
  src/main.tsx
  src/screens/FeaturedSearch.tsx
Labels: type: documentation, type: feature

#48 47 feat react router
  package-lock.json
  package.json
  src/App.tsx
  src/AppWrapper.tsx
  src/main.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/index.tsx
  vercel.json
Labels: type: feature

#50 ES Lint
  .eslintignore
  .eslintrc.json
  .github/workflows/eslint.yml
  README.md
  package-lock.json
  package.json
  src/AppWrapper.tsx
  src/components/SearchInput.tsx
  src/main.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/index.tsx
  vite.config.ts
Labels: type: feature

#62 46 feat db connection
  .env.template
  .gitignore
  package-lock.json
  package.json
  src/AppWrapper.tsx
  src/helpers/supabaseClient.ts
  src/main.tsx
  src/screens/DashboardScreen.tsx
  src/screens/LoginScreen.tsx
  src/screens/SignupScreen.tsx
  src/screens/index.tsx
  tsconfig.json
Labels: type: feature

#56 Create initial component structure
  .gitignore
  README.md
  package.json
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/SideNavigator.tsx
  src/components/index.ts
  src/main.tsx
  src/screens/DashboardScreen.tsx
  src/screens/LoginScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/SignupScreen.tsx
  src/screens/index.ts
Labels: type: feature

#76 Create types directory and move User and Session to it
  src/AppWrapper.tsx
  src/types/index.ts
  src/types/supabase.ts
Labels: type: feature

#78 68 feat auth error handling
  src/AppWrapper.tsx
  src/components/ErrorMessage.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/SideNavigator.tsx
  src/hooks/context.ts
  src/hooks/index.ts
  src/main.tsx
  src/screens/DashboardScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/LoginScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/SignupScreen.tsx
  src/screens/index.ts
  src/types/supabase.ts
Labels: type: feature, type: refactor

#83 69 refactor authentication
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/main.tsx
  src/screens/AuthScreen.tsx
  src/screens/index.ts
Labels: type: refactor

#85 59-feat-moviecard
  .env.template
  src/components/ShowCard.tsx
  src/helpers/getMovieUtils.ts
  src/screens/SearchResultsScreen.tsx
  src/types/supabase.ts
  src/types/tmdb.ts
Labels: type: feature

#87 79 feat supabase crud
  src/AppWrapper.tsx
  src/components/auth/SignupForm.tsx
  src/screens/DashboardScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/supabase/profiles.ts
  src/types/supabase.ts
Labels: type: feature

#90 Added env flags to documentation
  README.md
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
Labels: type: documentation

#94 43 feat test suite
  .github/workflows/ci.yml
  .github/workflows/eslint.yml
  README.md
  package-lock.json
  package.json
  src/__tests__/components/assets/movieData.ts
  src/__tests__/components/component.test.tsx
  src/__tests__/routes.tsx
  src/__tests__/screens/screen.test.tsx
  src/__tests__/setup.ts
  src/components/ErrorMessage.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/index.ts
  src/main.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/types/tmdb.ts
  tsconfig.json
  vitest.config.ts
Labels: type: feature

#105 92 feat card layout
  src/components/ShowCard.tsx
  src/screens/SearchResultsScreen.tsx
Labels: type: feature, type: refactor, type: enhancement

#108 Create git pre-commit hook
  .githooks/pre-commit
  package.json
Labels: type: feature

#115 Add watch queue methods to supabase util file
  src/__tests__/components/component.test.tsx
  src/__tests__/routes.tsx
  src/components/ShowCard.tsx
  src/supabase/profiles.ts
Labels: type: feature, priority: medium

#118 Update node version in github action
  .github/workflows/ci.yml
Labels: type: bug

#117 110 feat nav
  src/AppWrapper.tsx
  src/components/Navigation.tsx
Labels: type: feature

#119 Installed MUI and MUI Icons
  package-lock.json
  package.json
Labels: type: feature

#121 103 feat tw
  package-lock.json
  package.json
  postcss.config.cjs
  src/index.css
  tailwind.config.cjs
Labels: type: feature, type: enhancement

#122 Create dependabot.yml
  .github/dependabot.yml
Labels: type: feature

#123 Create SECURITY.md
  SECURITY.md
Labels: type: documentation

#132 Downmerge main -> develop
  package-lock.json
  package.json
Labels: type: enhancement

#133 Update dependabot config
  .github/dependabot.yml
Labels: type: enhancement, tag: security

#134 Create docs directory and add in files from wiki
  docs/contribution-guidelines.md
  docs/project-board.md
Labels: type: documentation

#138 Add basic theme switcher
  src/__tests__/setup.ts
  src/components/Navigation.tsx
  tailwind.config.cjs
Labels: type: feature, type: enhancement

#142 124 watch queue crud enhancement
  .githooks/pre-commit
  src/components/ShowCard.tsx
  src/screens/DashboardScreen.tsx
  src/supabase/profiles.ts
Labels: type: enhancement

#144 Profile Context
  .githooks/pre-commit
  src/AppWrapper.tsx
  src/components/Navigation.tsx
  src/components/ShowCard.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/helpers/getMovieUtils.ts
  src/hooks/context.ts
  src/hooks/index.ts
  src/screens/AuthScreen.tsx
  src/screens/DashboardScreen.tsx
  src/types/index.ts
Labels: type: refactor, priority: medium, type: enhancement
