Repository Thenlie/Streamability, pull requests merged in 2023-02, with the labels that each got.

#303 Added es-lint rule to warn on console logs. Ignored current logs.
  .eslintrc.json
  src/AppWrapper.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/screens/DashboardScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/supabase/profiles.ts
Labels: type: enhancement

#304 Added MUI stars for show reviews
  src/components/ShowCard.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: feature

#311 310 feat trending tv
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/screens/DiscoverScreen.tsx
Labels: type: feature

#319 Add adult flag and country profile setter functions
  src/screens/DashboardScreen.tsx
  src/supabase/profiles.ts
  src/types/supabase.ts
Labels: type: feature

#328 327 Fix CI
  .github/workflows/ci.yml
Labels: type: bug

#337 Convert dashboard to MUI components
  src/screens/DashboardScreen.tsx
Labels: type: enhancement
