Repository Thenlie/Streamability, pull requests merged in 2023-09, with the labels that each got.

#515 Dashboard refactor
  src/components/ShowListCard.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/index.ts
  src/components/modals/ConfirmDeleteModal.tsx
  src/components/modals/EditProfileModal.tsx
  src/components/modals/index.ts
  src/hooks/context.ts
  src/screens/DashboardScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/stories/constants.ts
  src/stories/modals/ConfirmDelete.stories.ts
  src/stories/modals/EditProfileModal.stories.ts
  src/types/supabase.ts
Labels: type: refactor, type: storybook

#519 Convert components to use React.FC
  src/components/ErrorMessage.tsx
  src/components/Navigation.tsx
  src/components/Providers.tsx
  src/components/Rating.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/loaders/ProvidersLoader.tsx
  src/components/loaders/ShowCardLoader.tsx
  src/components/loaders/ShowCarouselLoader.tsx
  src/components/loaders/ShowListCardLoader.tsx
  src/components/loaders/ShowPosterLoader.tsx
  src/components/modals/ConfirmDeleteModal.tsx
  src/components/modals/EditProfileModal.tsx
  src/screens/AuthScreen.tsx
  src/screens/DashboardScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/loaders/ShowDetailsLoader.tsx
Labels: type: refactor

#525 Logo
  README.md
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-384x384.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/fonts/Sunday Grapes.ttf
  public/images/logo-transparent.png
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  public/vite.svg
  src/components/Navigation.tsx
  src/index.css
  src/screens/FeaturedSearchScreen.tsx
Labels: type: feature, type: design

#526 View state local storage
  src/screens/SearchResultsScreen.tsx
Labels: type: enhancement

#529 add queue, favorite, watched buttons to details screen
  src/components/Navigation.tsx
  src/components/ShowCarousel.tsx
  src/hooks/index.ts
  src/hooks/useIsInFavorites.ts
  src/hooks/useIsInWatched.ts
  src/hooks/useWindowSize.ts
  src/index.css
  src/screens/FeaturedSearchScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/supabase.ts
Labels: type: feature, type: enhancement

#536 Dependabot/npm and yarn/develop/storybook/react vite 7.4.0
  package-lock.json
  package.json
  scripts/clean.sh
Labels: dependencies

#535 Show poster 'remove from queue' button
  src/components/ShowCarousel.tsx
  src/components/ShowPoster.tsx
  src/index.css
  src/screens/DashboardScreen.tsx
  src/stories/components/ShowPoster.stories.ts
  tailwind.config.cjs
Labels: type: enhancement

#550 537 Create show poster buttons
  src/components/Button.tsx
  src/components/IconButton.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useIsInFavorites.ts
  src/hooks/useIsInProfileArray.ts
  src/hooks/useIsInQueue.ts
  src/hooks/useIsInWatched.ts
  src/hooks/useProfileActions.ts
  src/screens/DashboardScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/stories/components/IconButton.stories.ts
  src/stories/components/ShowCarousel.stories.ts
  src/stories/components/ShowPoster.stories.ts
  src/stories/example/Button.stories.ts
  src/stories/example/Button.tsx
  src/stories/example/Header.stories.ts
  src/stories/example/Header.tsx
  src/stories/example/Page.stories.ts
  src/stories/example/Page.tsx
  src/stories/example/button.css
  src/stories/example/header.css
  src/stories/example/page.css
  src/types/supabase.ts
Labels: type: feature, type: refactor, type: enhancement

#552 539 useTrendingShows hook
  src/components/EmptySearchResults.tsx
  src/hooks/index.ts
  src/hooks/useTrendingShows.ts
  src/screens/DiscoverScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
Labels: type: enhancement

#555 523 Snackbar component
  src/__tests__/components/component.test.tsx
  src/components/Button.tsx
  src/components/ErrorMessage.tsx
  src/components/Snackbar.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/index.ts
  src/components/modals/ConfirmDeleteModal.tsx
  src/components/modals/EditProfileModal.tsx
  src/screens/DashboardScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/stories/components/Button.stories.ts
  src/stories/components/ErrorMessage.stories.ts
  src/stories/components/IconButton.stories.ts
  src/stories/components/Snackbar.stories.ts
Labels: type: feature, type: storybook

#556 548 Typography update
  src/components/EmptySearchResults.tsx
  src/components/Navigation.tsx
  src/components/Rating.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/ShowListCard.tsx
  src/components/auth/LoginForm.tsx
  src/components/modals/ConfirmDeleteModal.tsx
  src/components/modals/EditProfileModal.tsx
  src/logger.ts
  src/screens/DashboardScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: refactor

#561 Footer Component
  package-lock.json
  package.json
  public/images/JustWatch-large.png
  public/images/JustWatch.png
  public/images/tmdb.svg
  src/AppWrapper.tsx
  src/components/Footer.tsx
  src/components/index.ts
Labels: type: feature

#563 527 Details page sign up CTA
  src/screens/ShowDetailsScreen.tsx
Labels: type: enhancement

#567 README and Docs update
  README.md
  docs/contribution-guidelines.md
  docs/storybook.md
  docs/usage.md
Labels: type: documentation

#564 Add auth redirect buttons
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
Labels: type: enhancement

#565 Profile edit loading state
  src/components/modals/EditProfileModal.tsx
  src/helpers/showSortUtils.ts
  src/screens/DashboardScreen.tsx
Labels: type: enhancement

#566 Sorting search results
  src/helpers/getShowUtils.ts
  src/screens/SearchResultsScreen.tsx
  src/types/tmdb/movie.ts
  src/types/tmdb/show.ts
  src/types/tmdb/tv.ts
Labels: type: feature
