Repository Thenlie/Streamability, pull requests merged in 2023-10, with the labels that each got.

#572 Add verbose flag to clean script
  scripts/clean.sh
Labels: type: enhancement

#580 Create storybook docs
  src/stories/GettingStarted.mdx
  src/stories/assets/install.png
  src/stories/assets/running.png
Labels: type: documentation, type: storybook

#579 524 refactor text input component
  src/components/SearchInput.tsx
  src/components/TextInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/index.ts
  src/components/modals/EditProfileModal.tsx
  src/stories/components/TextInput.stories.ts
Labels: type: enhancement

#577 Filled out the MUI theme, bugfixes
  postcss.config.cjs
  public/fonts/Sunday Grapes.ttf
  src/AppWrapper.tsx
  src/components/Button.tsx
  src/components/EmptySearchResults.tsx
  src/components/Footer.tsx
  src/components/IconButton.tsx
  src/components/Navigation.tsx
  src/components/Providers.tsx
  src/components/SearchInput.tsx
  src/components/SearchResultCards.tsx
  src/components/ShowCard.tsx
  src/components/ShowCarousel.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/components/TextInput.tsx
  src/components/auth/SignupForm.tsx
  src/components/loaders/ProvidersLoader.tsx
  src/components/modals/EditProfileModal.tsx
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/index.css
  src/screens/FeaturedSearchScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/stories/components/IconButton.stories.ts
  src/theme.ts
  src/types/tmdb/show.ts
  tailwind.config.cjs
Labels: type: design, type: enhancement

#588 List todos
  TODO.md
  package-lock.json
  package.json
  src/__tests__/components/component.test.tsx
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/index.css
  src/supabase/profiles.ts
Labels: type: feature

#600 Create pull request template
  .github/pull_request_template.md
Labels: type: documentation, type: feature

#596 Dashboard carousels
  src/hooks/index.ts
  src/hooks/useGetProfileArray.ts
  src/screens/DashboardScreen.tsx
  src/supabase/profiles.ts
Labels: type: feature

#609 View all dashboard arrays
  TODO.md
  src/__tests__/routes.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/hooks/useProfileActions.ts
  src/main.tsx
  src/screens/auth/AuthLayout.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/auth/index.ts
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardLayout.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/dashboard/index.ts
  src/screens/index.ts
  src/screens/loaders/DashboardGalleryLoader.tsx
  src/screens/loaders/index.ts
Labels: type: feature

#611 Screen loaders & refactors
  TODO.md
  src/__tests__/routes.tsx
  src/components/EmptySearchResults.tsx
  src/components/index.ts
  src/main.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/index.ts
  src/screens/loaders/DashboardGalleryLoader.tsx
  src/screens/loaders/SearchResultsLoader.tsx
  src/screens/loaders/index.ts
  src/screens/search_results/EmptySearchResults.tsx
  src/screens/search_results/SearchResultsCards.tsx
  src/screens/search_results/SearchResultsHeader.tsx
  src/screens/search_results/SearchResultsScreen.tsx
  src/screens/search_results/index.ts
Labels: type: refactor, type: enhancement

#612 Fix auth endpoint bug
  src/components/Navigation.tsx
  src/main.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
Labels: type: bug

#614 Country validation
  src/components/modals/EditProfileModal.tsx
  src/helpers/__tests__/validation.test.ts
  src/helpers/index.ts
  src/helpers/validationUtils.ts
  src/screens/auth/SignUpScreen.tsx
Labels: type: enhancement

#616 add MUI theme to storybook
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/theme.ts
Labels: type: storybook

#628 fix storybook clicks
  .storybook/main.ts
  package-lock.json
  package.json
  src/stories/components/ShowCard.stories.ts
  src/stories/components/ShowCarousel.stories.ts
  src/stories/components/ShowListCard.stories.ts
  src/stories/components/ShowPoster.stories.ts
Labels: type: bug

#629 Refactor Carousel Loading
  src/components/ShowCarousel.tsx
  src/components/loaders/ShowCarouselLoader.tsx
  src/hooks/__tests__/useGetProfileArray.test.ts
  src/hooks/useGetProfileArray.ts
  src/screens/FeaturedSearchScreen.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/search_results/EmptySearchResults.tsx
Labels: type: enhancement

#639 Discover Screen Refactor
  TODO.md
  diff.patch
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/screens/DiscoverScreen.tsx
  src/types/tmdb/movie.ts
  src/types/tmdb/tv.ts
Labels: type: feature

#640 Empty dashboard gallery
  public/images/resting.svg
  src/AppWrapper.tsx
  src/components/Navigation.tsx
  src/components/ShowCarousel.tsx
  src/helpers/index.ts
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/dashboard/DashboardEmptyGallery.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/supabase/profiles.ts
  src/supabase/supabaseClient.ts
Labels: type: enhancement

#641 Show details button fix
  src/screens/ShowDetailsScreen.tsx
Labels: type: bug

#642 Refactor carousel loader
  src/components/ShowCarousel.tsx
  src/components/loaders/ShowCarouselLoader.tsx
  src/components/loaders/ShowPosterLoader.tsx
  src/hooks/__tests__/useGetProfileArray.test.ts
  src/hooks/__tests__/useTrendingShows.test.ts
  src/hooks/useGetProfileArray.ts
  src/hooks/useTrendingShows.ts
  src/screens/loaders/ShowDetailsLoader.tsx
  src/stories/loaders/ShowCarouselLoader.stories.ts
Labels: type: refactor

#645 Supabase CLI
  docs/usage.md
  package-lock.json
  package.json
  scripts/db-start.sh
  supabase/.gitignore
  supabase/config.toml
  supabase/functions/.vscode/extensions.json
  supabase/functions/.vscode/settings.json
  supabase/migrations/20231023025032_initial_migration.sql
  supabase/seed.sql
Labels: type: feature, type: database

#664 fix dashboard empty gallery padding
  src/screens/dashboard/DashboardEmptyGallery.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
Labels: type: refactor

#666 fix signup error 😈
  TODO.md
  src/hooks/useGetProfileArray.ts
  src/screens/auth/SignUpScreen.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/loaders/DashboardGalleryLoader.tsx
Labels: type: bug

#669 Banner Loader & Bug Fix
  src/components/Banner.tsx
  src/screens/DiscoverScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
Labels: type: bug, type: feature

#670 Show card refactor
  src/__tests__/routes.tsx
  src/components/ShowCard.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/components/loaders/ShowCardLoader.tsx
  src/screens/search_results/SearchResultsCards.tsx
  src/stories/components/ShowCard.stories.ts
  src/stories/components/ShowListCard.stories.ts
Labels: type: refactor

#672 Notify users of offline state
  src/components/OfflineSnackbar.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useNetworkStatus.ts
  src/hooks/useTrendingShows.ts
  src/screens/DiscoverScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/auth/AuthLayout.tsx
  src/screens/dashboard/DashboardLayout.tsx
  src/screens/search_results/SearchResultsScreen.tsx
Labels: type: feature

#675 fix 'person' media_type bug
  src/helpers/__tests__/showFilter.test.ts
  src/helpers/getShowUtils.ts
  src/helpers/showFilterUtils.ts
  src/types/tmdb/show.ts
Labels: type: bug

#676 Add pagination to search results screen
  .gitignore
  src/__tests__/screens/assets/showData.ts
  src/helpers/getMovieUtils.ts
  src/helpers/getShowUtils.ts
  src/helpers/getTvUtils.ts
  src/helpers/index.ts
  src/helpers/showTypeUtils.ts
  src/hooks/__tests__/constants.ts
  src/hooks/index.ts
  src/hooks/usePaginatedData.ts
  src/screens/search_results/SearchResultsCards.tsx
  src/screens/search_results/SearchResultsHeader.tsx
  src/screens/search_results/SearchResultsScreen.tsx
  src/stories/constants.ts
  src/types/tmdb/movie.ts
  src/types/tmdb/show.ts
  src/types/tmdb/tv.ts
Labels: type: feature

#677 Fix runtime '0' bug
  src/screens/ShowDetailsScreen.tsx
Labels: type: bug

#678 Discover media type
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/helpers/showTypeUtils.ts
Labels: type: bug

#679 Fix show poster aspect ration to 2:3
  src/components/ShowPoster.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: enhancement

#680 TV Detail Enhancements
  src/helpers/showTypeUtils.ts
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb/show.ts
  src/types/tmdb/tv.ts
Labels: type: feature, type: enhancement

#690 Add daysAgo helper function
  src/helpers/dateFormatUtils.ts
Labels: type: feature

#682 fix search results bugs
  src/components/ShowPoster.tsx
  src/screens/search_results/SearchResultsScreen.tsx
Labels: type: bug

#681 Add carousel title and button
  src/components/ShowCarousel.tsx
  src/index.css
  src/screens/DiscoverScreen.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/stories/components/ShowCarousel.stories.ts
Labels: type: enhancement

#689 Create dashboard skeleton loader
  TODO.md
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/loaders/DashboardLoader.tsx
  src/screens/loaders/index.ts
  src/stories/loaders/ShowCarouselLoader.stories.ts
Labels: type: enhancement

#692 Add unit tests
  TODO.md
  src/helpers/__tests__/constants.ts
  src/helpers/__tests__/dateFormat.test.ts
  src/helpers/__tests__/stringFormat.test.ts
  src/helpers/dateFormatUtils.ts
  src/helpers/stringFormatUtils.ts
  src/screens/ShowDetailsScreen.tsx
Labels: type: testing

#693 switch nav input from outlined to filled
  src/components/SearchInput.tsx
Labels: type: refactor
