Repository Thenlie/Streamability, pull requests merged in 2023-01, with the labels that each got.

#228 Add helper functions to test dir. Refactor tests slightly.
  src/__tests__/components/component.test.tsx
  src/__tests__/helpers/navigation.ts
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/components/SearchInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
Labels: type: testing

#235 Refactor show card component to use MUI components
  src/components/ShowCard.tsx
  src/screens/SearchResultsScreen.tsx
Labels: type: design, type: enhancement

#236 199 test invalid auth
  src/__tests__/helpers/navigation.ts
  src/__tests__/screens/authScreen.test.tsx
  src/components/auth/SignupForm.tsx
Labels: type: testing

#241 Add NO_VERIFY flag check to pre-commit hook. Update docs
  .githooks/pre-commit
  docs/contribution-guidelines.md
Labels: type: enhancement

#244 227 feat tv req
  src/__tests__/routes.tsx
  src/__tests__/screens/assets/showData.json
  src/__tests__/screens/movieScreen.test.tsx
  src/components/Providers.tsx
  src/components/ShowCard.tsx
  src/helpers/getMovieUtils.ts
  src/helpers/getShowUtils.ts
  src/screens/DiscoverScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb.ts
Labels: type: feature, type: enhancement

#253 Refactor types, add comments, improve test mocks.
  .prettierrc.json
  src/__tests__/routes.tsx
  src/__tests__/screens/assets/showData.json
  src/__tests__/screens/movieScreen.test.tsx
  src/components/Providers.tsx
  src/components/ShowCard.tsx
  src/components/SideNavigator.tsx
  src/components/index.ts
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/screens/DiscoverScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/index.ts
  src/types/supabase.ts
  src/types/tmdb.ts
Labels: type: enhancement

#265 v1.4.1 Develop
  package-lock.json
  package.json
Labels: dependencies

#267 Create LICENSE
  LICENSE
Labels: type: documentation

#273 162 theme provider
  .githooks/pre-commit
  src/AppWrapper.tsx
  src/components/Navigation.tsx
  src/components/SearchInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/index.css
  src/theme.ts
Labels: type: design

#276 237 feat recommendations
  src/__tests__/screens/movieScreen.test.tsx
  src/components/ShowCard.tsx
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/screens/DiscoverScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/index.ts
  src/types/tmdb.ts
Labels: type: feature

#277 Refactor SearchResultsPage to not use details query
  src/__tests__/screens/assets/index.ts
  src/__tests__/screens/assets/providerData.json
  src/__tests__/screens/assets/providerData.ts
  src/__tests__/screens/assets/showData.json
  src/__tests__/screens/assets/showData.ts
  src/__tests__/screens/movieScreen.test.tsx
  src/components/ShowCard.tsx
  src/helpers/getMovieUtils.ts
  src/helpers/getTvUtils.ts
  src/screens/DiscoverScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb.ts
Labels: type: refactor, type: enhancement

#278 Convert show details screen to allow Movie or TV show
  src/__tests__/routes.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/components/ShowCard.tsx
  src/main.tsx
  src/screens/DiscoverScreen.tsx
  src/screens/SearchResultsScreen.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: refactor, type: enhancement

#280 193 placeholder poster
  public/poster-placeholder.jpeg
  src/components/ShowCard.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: enhancement

#287 Create showCard skeleton loader
  package-lock.json
  package.json
  src/components/ShowCardPlaceholder.tsx
  src/components/index.ts
  src/screens/SearchResultsScreen.tsx
Labels: type: feature, type: design

#291 288 Create CODEOWNERS
  .github/CODEOWNERS
Labels: type: documentation

#290 Add skeleton loader theme
  src/AppWrapper.tsx
  src/theme.ts
Labels: type: design, type: enhancement

#292 Loop through array of release dates to find a non-empty rating
  src/helpers/getMovieUtils.ts
Labels: type: bug

#293 Conditionally rendering runtime
  src/helpers/getTvUtils.ts
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb.ts
Labels: type: bug
