Repository Thenlie/Streamability, pull requests merged in 2023-11, with the labels that each got.

#698 Re-enable UI test
  TODO.md
  docs/contribution-guidelines.md
  docs/testing.md
  package-lock.json
  package.json
  src/__tests__/components/component.test.tsx
  src/__tests__/constants.ts
  src/__tests__/helpers/navigation.ts
  src/__tests__/routes.tsx
  src/__tests__/screens/FeaturedSearchScreen.test.tsx
  src/__tests__/screens/PageNotFoundScreen.test.tsx
  src/__tests__/screens/SearchResultsScreen.test.tsx
  src/__tests__/screens/ShowDetailsScreen.test.tsx
  src/__tests__/screens/assets/index.ts
  src/__tests__/screens/assets/movieData.json
  src/__tests__/screens/assets/providerData.ts
  src/__tests__/screens/assets/searchData.json
  src/__tests__/screens/assets/showData.ts
  src/__tests__/screens/authScreen.test.tsx
  src/__tests__/screens/movieScreen.test.tsx
  src/__tests__/screens/navigation.test.tsx
  src/components/Banner.tsx
  src/components/Navigation.tsx
  src/components/Providers.tsx
  src/components/SearchInput.tsx
  src/components/ShowCarousel.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/components/loaders/BannerLoader.tsx
  src/components/loaders/ShowCarouselLoader.tsx
  src/helpers/__tests__/dateFormat.test.ts
  src/hooks/__tests__/useTrendingShows.test.ts
  src/hooks/useTrendingShows.ts
  src/main.tsx
  src/routes.tsx
  src/screens/FeaturedSearchScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/loaders/SearchResultsLoader.tsx
  src/screens/search_results/EmptySearchResults.tsx
  src/screens/search_results/SearchResultsHeader.tsx
  src/screens/search_results/SearchResultsScreen.tsx
  src/stories/components/Banner.stories.ts
  vitest.config.ts
  vitest.setup.ts
Labels: type: testing

#704 create empty show details screen
  TODO.md
  public/images/error.svg
  src/__tests__/screens/PageNotFoundScreen.test.tsx
  src/__tests__/screens/ShowDetailsScreen.test.tsx
  src/screens/EmptyShowDetailsScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: feature

#715 Fix TV Show details bug
  src/helpers/showTypeUtils.ts
  src/types/tmdb/tv.ts
Labels: type: bug

#713 Buttons to sort by Show Type on Search Details Screens
  src/screens/search_results/SearchResultsHeader.tsx
  src/screens/search_results/SearchResultsScreen.tsx
Labels: type: feature

#717 Authentication screen tests
  src/__tests__/screens/FeaturedSearchScreen.test.tsx
  src/__tests__/screens/LoginScreen.test.tsx
  src/__tests__/screens/PageNotFoundScreen.test.tsx
  src/__tests__/screens/SearchResultsScreen.test.tsx
  src/__tests__/screens/ShowDetailsScreen.test.tsx
  src/__tests__/screens/SignUpScreen.test.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
Labels: type: testing

#707 Improve docs
  .env.template
  README.md
  docs/contribution-guidelines.md
  docs/getting-started.md
  docs/project-board.md
  docs/storybook.md
  docs/supabase.md
  docs/testing.md
  docs/usage.md
Labels: type: documentation

#718 Page not found illustration
  public/images/404.svg
  src/__tests__/screens/PageNotFoundScreen.test.tsx
  src/screens/PageNotFoundScreen.tsx
Labels: type: enhancement

#720 Update to node 20
  .github/workflows/ci.yml
  .tool-versions
Labels: type: enhancement

#721 Dashboard UI tests
  docs/getting-started.md
  src/__tests__/constants.ts
  src/__tests__/screens/DashboardGalleryScreen.test.tsx
  src/__tests__/screens/DashboardScreen.test.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
Labels: type: testing

#729 clear search input after submitting search
  src/components/SearchInput.tsx
Labels: type: enhancement

#730 Automate TODO script
  .github/workflows/ci.yml
  TODO.md
Labels: type: enhancement

#733 #731 improve logger class
  src/logger.ts
Labels: type: enhancement

#734 #578 fix scroll overflow color
  index.html
  src/AppWrapper.tsx
Labels: type: enhancement

#735 #647 Resolve form label error
  src/components/SearchInput.tsx
  src/screens/auth/SignUpScreen.tsx
Labels: type: bug

#751 Create actor card component and storybook
  src/components/ActorCard.tsx
  src/components/index.ts
  src/stories/components/ActorCard.stories.ts
  src/stories/constants.ts
  src/types/tmdb/actor.ts
  src/types/tmdb/index.ts
Labels: type: feature, type: storybook

#752 Add cast list to show detail screen
  src/components/ActorCard.tsx
  src/helpers/getMovieUtils.ts
  src/helpers/showTypeUtils.ts
  src/screens/ShowDetailsScreen.tsx
  src/types/tmdb/movie.ts
  src/types/tmdb/show.ts
  src/types/tmdb/tv.ts
Labels: type: feature

#765 Actor detail screen
  TODO.md
  src/components/ActorCard.tsx
  src/helpers/getActorUtils.ts
  src/helpers/getMovieUtils.ts
  src/helpers/index.ts
  src/helpers/showTypeUtils.ts
  src/routes.tsx
  src/screens/ActorDetailScreen.tsx
  src/screens/index.ts
  src/types/tmdb/actor.ts
Labels: type: feature
