Repository Thenlie/Streamability, pull requests merged in 2024-12, with the labels that each got.

#1091 Center empty carousel text
  TODO.md
  src/components/ShowCarousel.tsx
Labels: type: enhancement

#1092 add dependabot group for @types dependencies
  .github/dependabot.yml
Labels: dependencies

#1093 bump react router dom 7.0.1
  TODO.md
  package-lock.json
  package.json
  src/AppWrapper.tsx
  src/__tests__/components/ActorCard.test.tsx
  src/__tests__/components/ShowCard.test.tsx
  src/__tests__/components/ShowListCard.test.tsx
  src/__tests__/components/ShowPoster.test.tsx
  src/__tests__/screens/DashboardGalleryScreen.test.tsx
  src/__tests__/screens/DashboardScreen.test.tsx
  src/__tests__/screens/DiscoverScreen.test.tsx
  src/__tests__/screens/FeaturedSearchScreen.test.tsx
  src/__tests__/screens/LoginScreen.test.tsx
  src/__tests__/screens/PageNotFoundScreen.test.tsx
  src/__tests__/screens/SearchResultsScreen.test.tsx
  src/__tests__/screens/ShowDetailsScreen.test.tsx
  src/__tests__/screens/SignUpScreen.test.tsx
  src/components/ActorCard.tsx
  src/components/Footer.tsx
  src/components/Navigation.tsx
  src/components/SearchInput.tsx
  src/components/ShowCard.tsx
  src/components/ShowListCard.tsx
  src/components/ShowPoster.tsx
  src/hooks/context.ts
  src/main.tsx
  src/routes.tsx
  src/screens/ActorDetailScreen.tsx
  src/screens/EmptyActorDetailScreen.tsx
  src/screens/EmptyShowDetailsScreen.tsx
  src/screens/PageNotFoundScreen.tsx
  src/screens/ShowDetailsScreen.tsx
  src/screens/auth/AuthLayout.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/dashboard/DashboardGalleryScreen.tsx
  src/screens/dashboard/DashboardLayout.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/screens/discover/DiscoverScreen.tsx
  src/screens/loaders/DashboardGalleryLoader.tsx
  src/screens/search_results/EmptySearchResults.tsx
  src/screens/search_results/SearchResultsScreen.tsx
Labels: dependencies

#1104 Remove cast section when no cast list is provided
  src/screens/ShowDetailsScreen.tsx
Labels: type: enhancement

#1110 add custom scrollbar styles for better aesthetics
  src/index.css
Labels: type: enhancement

#1107 improve email validation regex in Login and SignUp screens
  TODO.md
  src/helpers/validationUtils.ts
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignUpScreen.tsx
Labels: type: bug

#1106 748 fix lighthouse seo audit
  index.html
  src/components/Banner.tsx
  src/components/Navigation.tsx
  src/screens/ActorDetailScreen.tsx
  src/screens/EmptyActorDetailScreen.tsx
  src/screens/EmptyShowDetailsScreen.tsx
  src/screens/dashboard/DashboardEmptyGallery.tsx
  src/screens/search_results/EmptySearchResults.tsx
Labels: type: enhancement

#1111 feat: add crew section to ShowDetailsScreen
  src/components/ActorCard.tsx
  src/screens/ShowDetailsScreen.tsx
Labels: type: feature
