Repository Thenlie/Streamability, pull requests merged in 2025-04, with the labels that each got.

#1220 ESLint 9.* Migration
  .eslintignore
  .eslintrc.json
  .prettierrc
  cli/fetch.ts
  cli/searchSelect.ts
  eslint.config.js
  package-lock.json
  package.json
  src/components/Banner.tsx
  src/helpers/__tests__/constants.ts
  src/helpers/getShowUtils.ts
  src/stories/modals/ConfirmDelete.stories.ts
Labels: dependencies

#1225 Add test case for show list card queue button
  src/__tests__/components/ShowListCard.test.tsx
  src/__tests__/constants.ts
  src/supabase/profiles.ts
Labels: type: testing

#1227 Update various npm dependencies (minor/patch)
  package-lock.json
  package.json
Labels: dependencies

#1229 Fix various storybook issues
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.js
  src/components/Providers.tsx
  src/screens/ShowDetailsScreen.tsx
  src/stories/Configure.mdx
  src/stories/GettingStarted.mdx
  src/stories/components/Providers.stories.ts
Labels: type: bug

#1236 remove people from show search results
  src/hooks/usePaginatedData.ts
Labels: type: bug

#1237 Fix queue button flicker
  src/hooks/useIsInProfileArray.ts
Labels: type: bug
