Repository Thenlie/Streamability, pull requests merged in 2025-01, with the labels that each got.

#1109 811 create in theatres section
  src/helpers/getMovieUtils.ts
  src/helpers/showTypeUtils.ts
  src/hooks/index.ts
  src/hooks/useInTheatersShows.ts
  src/screens/FeaturedSearchScreen.tsx
Labels: type: feature

#1118 fix: todo file and featured search test
  TODO.md
  src/__tests__/screens/FeaturedSearchScreen.test.tsx
Labels: type: bug

#1132 Add cast to TV Shows
  src/helpers/getTvUtils.ts
Labels: type: enhancement
